// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd1542EWmQxfZAjkC8uPYT9hKhljm_DI4',
    appId: '1:229408826175:web:576a6373c56453c179698a',
    messagingSenderId: '229408826175',
    projectId: 'usingfirebase-9f02c',
    authDomain: 'usingfirebase-9f02c.firebaseapp.com',
    storageBucket: 'usingfirebase-9f02c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2aERW9q10EbS90-ZIrNSZSWyylsaDNU',
    appId: '1:229408826175:android:98e6fc569ee5f11979698a',
    messagingSenderId: '229408826175',
    projectId: 'usingfirebase-9f02c',
    storageBucket: 'usingfirebase-9f02c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvNZGvCp6w8qFRylyQq1bJFT04HRXbZMw',
    appId: '1:229408826175:ios:7d0e7d2233acca4779698a',
    messagingSenderId: '229408826175',
    projectId: 'usingfirebase-9f02c',
    storageBucket: 'usingfirebase-9f02c.appspot.com',
    iosBundleId: 'com.example.usingfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvNZGvCp6w8qFRylyQq1bJFT04HRXbZMw',
    appId: '1:229408826175:ios:6575f68f9a7a4b3279698a',
    messagingSenderId: '229408826175',
    projectId: 'usingfirebase-9f02c',
    storageBucket: 'usingfirebase-9f02c.appspot.com',
    iosBundleId: 'com.example.usingfirebase.RunnerTests',
  );
}
